// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuntAr-0c8IptKWT6wFdu6ypOjclPaFw',
    appId: '1:190307395844:web:be76abe91eba0d1a1c0851',
    messagingSenderId: '190307395844',
    projectId: 'ui8-web',
    authDomain: 'ui8-web.firebaseapp.com',
    storageBucket: 'ui8-web.appspot.com',
    measurementId: 'G-THHKR9FTH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxlCfSilqsstMPBchYFauA2Pp5s3AO7-k',
    appId: '1:190307395844:android:e558a463b081564e1c0851',
    messagingSenderId: '190307395844',
    projectId: 'ui8-web',
    storageBucket: 'ui8-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PND2aNjBScLbhz9Nu4wwxU-aChBB4ns',
    appId: '1:190307395844:ios:3e89ae6104263e091c0851',
    messagingSenderId: '190307395844',
    projectId: 'ui8-web',
    storageBucket: 'ui8-web.appspot.com',
    iosBundleId: 'com.uii8.folio',
  );
}
